version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: basquetkids_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basquetkids
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: basquetkids_web
    container_name: basquetkids_web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: basquetkids
